pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Jenkins File Inside folder"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
	
	}
	post {
        always {
            echo 'This will always run'
	    emailext body: 'Sent using Jenkinsfile2 inside folder😎', subject: 'Jenkinsfile pipeline testmail', to: 'saksham.gupta@daffodilsw.com'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
